package sumaApp;


/**
* sumaApp/sumaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sumaApp.idl
* lunes 9 de abril de 2018 07:54:31 PM COT
*/

public interface sumaOperations 
{
  int sumar (int primernumero, int segundonumero);
  void shutdown ();
} // interface sumaOperations
