package sumaApp;


/**
* sumaApp/suma.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sumaApp.idl
* lunes 9 de abril de 2018 07:54:31 PM COT
*/

public interface suma extends sumaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface suma
